# Required
site_name: CivicTechJobs Docs
site_url: https://example.com/

# Optionals
edit_uri: ""
extra_css:
  - css/extra.css
extra_javascript:
  - js/extra.js
nav:
  - Roles:
    - Product Manager:
      - Placeholder: about.md
    - UI Designer:
      - Placeholder: about.md
    - UX Researcher:
      - Placeholder: about.md
    - Web Developer:
      - CONTRIBUTING.md: https://github.com/hackforla/CivicTechJobs/blob/main/CONTRIBUTING.md#welcome-to-the-civictechjobs-contributing-guide
      - Backend Architecture: developer/backend.md
      - Developer Workflow Cycle: developer/developer-flow.md
      - Frontend Architecture: developer/frontend.md
      - GitHub Architecture: developer/github.md
      - Installation Instructions: developer/installation.md
  - Resources: resources.md
  - CivicTechJobs Repo: https://github.com/hackforla/CivicTechJobs
repo_url: https://github.com/Aveline-art/CivicTechJobs-Documentation/
repo_name: GitHub
theme:
  name: mkdocs
  nav_style: dark
  navigation_depth: 3
  locale: en
